### ISSUE TITLE
socket_sendto( /tmp/zm/zms-.sock ) failed: No such file or directory

### ISSUE THREAD

**Issue by zhjchen** [ZoneMinder/ZoneMinder#1009]
I know many people experienced similar issue. 
By google we can see some solutions there.

However, My issue is that zoneminder seems very unstable.
sometimes, I can see the camera video.
Sometimes, I cannot. It throws the sock missing failure. In such case, actually it creates /tmp/zm/zms-194391w.sock instead of /tmp/zm/zms-194391s.sock

I am using ubuntu 14.04.3
zoneminder is 1.28.1

**Comment by knnniggett** [comment]
While there are occasionally other cases, the number one reason for socket-sendto errors in your log files is an apache web server configuration issue.  In any case, this issue is neither a bug, not is it a feature request.  

Please see our posting rules:
https://github.com/ZoneMinder/ZoneMinder/wiki/Github-Posting-Rules

Consequently, this discussion belongs in the user forum.
