### ISSUE TITLE
620552 - zone definition page doesn't refresh after zone change

### ISSUE THREAD

**Issue by kylejohnson** [ZoneMinder/ZoneMinder#104]
http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=620552

**Comment by knnniggett** [comment]
I'm not experiencing this issue on my demo system.
@onlyjob Since this was reported as a Debian bug, would you mind letting us know if this has been resolved?

**Comment by onlyjob** [comment]
It was reported against old version of ZoneMinder so I suspect that the problem has been already resolved. I've just closed corresponding Debian bug and asked reporter to report it again for the current version of the package if this is still a problem. I believe it should be safe to close this bug here as well.

@kylejohnson, thank you for forwarding Debian bugs upstream. When Debian bugs are forwarded they are usually marked as "Forwarded" with corresponding URL of the upstream bug and taged "upstream". See how header of [620552](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=620552) looks like? :)
