### ISSUE TITLE
Filters do not work

### ISSUE THREAD

**Issue by luky7795** [ZoneMinder/ZoneMinder#1097]
Hello
I installed zoneminder 1.28 on raspbian wheezy, but do not send me email alert (postfix). So I tried to run zmfiltrer.pl it says:
Name "Net :: SFTP :: Foreign :: debug" used only once: possible typo at /usr/bin/zmfilter.pl line 928.
When I tested zoneminder on ubuntu 4.14 I have not had any problems.
 The link server is http://faggottino.ddns.net/zm/
Thank you in advance.

**Comment by knnniggett** [comment]
I'm sorry filters are not working on your system, but filters are known to work. Additionally, you have not provided any information to indicate this is a bug.

Please review our posting guidelines and then create a thread in the user forum:
https://github.com/ZoneMinder/ZoneMinder/wiki/Github-Posting-Rules

The thread should contain:
- How you installed zoneminder (package or source) and the exact version
- The output of zmfilter.pl after using proper command line syntax:
`zmfilter.pl [-f <filter name>,--filter=<filter name>] | -v, --version`
- Post the details of the filter you intend to run
- Post relevant the details of the email tab under options

You have a configuration problem somewhere, and there are several people in the user forum who can help you figure out where the problem is.

You should also search the user forum for existing topics as there have been a few others who worked through similar issues.
