### ISSUE TITLE
another socket_sendto issue

### ISSUE THREAD

**Issue by vobelic** [ZoneMinder/ZoneMinder#1237]
Strongly related to issue #563
Basically I added a new camera and did a dist-upgrade somewhere in between on my Ubuntu 14.04 system.
I'm using the PPA from Isaac Connor and there was also an upgrade from zoneminder:amd64 (1.28.1-trusty-1, 1.28.1-trusty-2).
Now Im getting my logs filled with 'socket_sendto( /var/run/zm/zms-xxxxxxs.sock ) failed: No such file or directory'.
Am AM able to view both my saved and live captures except everything is very slow.
Stopping/disabling the newly added camera doesn't help.

System
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"

$ cat /etc/zm/apache.conf 
Alias /cctv /usr/share/zoneminder

<Directory /usr/share/zoneminder>
  php_flag register_globals off
  Options Indexes FollowSymLinks
  <IfModule mod_dir.c>
    DirectoryIndex index.php
  </IfModule>
</Directory>

**Comment by knnniggett** [comment]
socket_sendto errors mean that zoneminder was not able to create a socket.
Just like issue #563, 99% of these errors are caused by a misconfiguration if your Apache Script Alias as it relates to PATH_ZMS under options. The other 1% are caused by incorrect permission on the socket folder or lack of free memory.

In any case, this is definitely not a bug. This discussion should be taken to the user forum.
