### ISSUE TITLE
Replay video event stop after few sec

### ISSUE THREAD

**Issue by christophey2k** [ZoneMinder/ZoneMinder#1267]
hi all, on recently fresh source install v1.29 on my gentoo, have à bug:

When i want to reply an recorded event, the video stop playing after few sec
(i use firefox 38.6 linux)

**Comment by knnniggett** [comment]
You have not provided any data to indicate you are experiencing a bug, and this is not the place to discuss installation or camera configurations issues.

Please create a post in the user forum, desribe you system, and how you installed zoneminder. If this issue is only with a single camera, then describe your camera and include screenshots of the configuration in zoneminder.

In all cases, we need to see a complete  copy of your logs.
