### ISSUE TITLE
Too much files, why single JPEGs?

### ISSUE THREAD

**Issue by gj12** [ZoneMinder/ZoneMinder#1456]
Hi,

I have a large ZM system with ca. 52000 events (one year). My problem is I can't backup the system under 2 days, because every frame is 1 JPEG file. It's actually more practicable for me to copy the whole 3 TB disc with dd. A normal copy process would take so much time, because every file create adds so much overhead. df -i shows me an inode usage of 41%.

Is there another practical solution for this? How do outher people beackup lots of events?

Why did nobody implemented video files? It would be easy to use them frame by frame with opencv.

**Comment by connortechnology** [comment]
Why? Because back when ZM was written, all cameras outputted jpgs.  
Also, because video is not trivial, despite what you think. We are working on it.

I don't think anyone tries to keep a year's worth of events.  And if they do, they are likely using incremental rsync backups or ongoing copies to another machine as events are created. 

And now I will close this, as it does not describe a bug.  Please take it to the forums at http://forums.zoneminder.com.
