### ISSUE TITLE
Authentication via LDAP / AD

### ISSUE THREAD

**Issue by peruchi** [ZoneMinder/ZoneMinder#1595]
it would be interesting to integrate with LDAP / AD, making bind, filters for groups, is a suggestion.

**Comment by knnniggett** [comment]
Per our posting guidelines, we only accept feature requests where you are willing to either a) write the code yourself or b) assign a sizeable bounty to the feature request to pay someone else to do the work.

Unless you plan on meeting one of those criteria soon, I am going to close this issue.

This does not mean we do not appreciate your idea. We get a lot of feature requests, but most won't get worked on due to lack of manpower.

**Comment by peruchi** [comment]
OK, you can close, I am studying the language and try to carry out this implementation and if successful, will make a pull request.

**Comment by knnniggett** [comment]
We are in the #zoneminder irc channel daily. That would be the best place to get to know the development team and ask code related questions.
