### ISSUE TITLE
issue #1942 merged yet somehow still an issue in 1.30.4 on debian install

### ISSUE THREAD

**Issue by christhephish** [ZoneMinder/zoneminder#2068]
ZM 1.30.4 installed on standalone metal via recommended 'ZM the easy debian way'

Debian 9 w/ kernel in stable repos.

log will not display intermittently, will export to txt file, however is still displaying issues that above listed #1942 merge should resolve.
```

      'TimeKey' => '1521299366.332613',
      'Component' => 'zmc_m2',
      'ServerId' => '0',
      'Pid' => '3413',
      'Level' => '-3',
      'Code' => 'FAT',
      'Message' => '_swscale does not support the codec format: ÿÿÿÿ',_
 
```

**Comment by knnniggett** [comment]
Look at the date #1942 was merged - July 6, 2017.
Now look at the date ZoneMinder 1.30.4 was released - May 9, 2017.

You have a few choices here. You can:
- File a bug report with Debian and ask them to patch the their current package
- Wait until the next ZoneMinder release and then wait for Debian to create an ew package (we have no control over this)
- Build your ZoneMinder package using the instructions from our readthedocs

I'm closing this issue out since this is not something we can "fix" on our end.
