### ISSUE TITLE
Multiple Storage Locations [$65]

### ISSUE THREAD

**Issue by Yamanipanuchi** [ZoneMinder/zoneminder#21]
The ability to Store events to multiple storage locations. Either by moving older events to long term storage or have specific camera's go to specific storage locations.
##

**Comment by delvasto1** [comment]
I was wondering if this had been fixed. 














I  have a fix for this by a modification of zmfilter.pl, I also made some changes to the events directory where I replaced the directory name with links to locations on multiple local disk drives,
and it would probably work with remote storage. I have been using this since 2009, when I had
tried to communicate with the zm people at that time, nobody responded. i amd using 1.29.0

**Comment by connortechnology** [comment]
There has been a lot of work on it.  My storageareas branch is pretty useful in this regard.  Expect it to be merged around 1.31
