### ISSUE TITLE
RTSP / SETUP problem without trackid causes reply with bad request 400

### ISSUE THREAD

**Issue by qpaz** [ZoneMinder/zoneminder#2118]
I see in wireshark with zm 1.31.1 the initial RTSP network stream SETUP packet was done with 
rtsp://hostname:port/path/trackID=X

In zm version 1.31.44 the initial RTSP SETUP packet is only
rtsp://hostname:port/path

I got a vivotek 8364 which fails in 1.31.44 on RTSP SETUP with 400 Bad Request

**Comment by connortechnology** [comment]
I have no issues with my 8136 or 8166's.  

Are you using Remote or FFmpeg?

**Comment by qpaz** [comment]
General
Source Type: Remote
Function: Modect
Source
Remote Protocol: RTSP
Remote Method: RTP/RTSP
Remote Host Name: <FQDN> 
Remote Host Port: 554
Remote Host Path: /live.sdp (vivotek specific)

Unitl now, this settings worked for years

**Comment by knnniggett** [comment]
Using the remote source type for ip cameras has been unsupported for some time now. See the documentation: http://zoneminder.readthedocs.io/en/stable/userguide/definemonitor.html#remote

You can certainly try to use the remote source type, but we aren't going to spend any time working on it if problems occur, since better solutions exist. 

You should use the ffmpeg source type instead.

**Comment by connortechnology** [comment]
The remote rtsp was using h264 passthrough code which does not work (only works for ffmpeg).  I have pushed a fix to stop this behaviour.  New packages are building.

**Comment by knnniggett** [comment]
Please be advised that we have agreed to remove the Remote->RTSP method, not in the next release, but in the release after. I will make sure and include a notice about this in the next release notes.
This will not affect the RTSP->HTTP source type.

It is in everyone's interest to switch to the ffmpeg method (or libvlc) for IP cameras as soon as possible.
