### ISSUE TITLE
flawed daemonization; bad design of `zmpkg.pl`; problematic detection of init system

### ISSUE THREAD

**Issue by onlyjob** [ZoneMinder/zoneminder#2177]
I've stumbled upon a problem when I could not start ZineMinder inside _rkt_ container because `zmpkg.pl` makes unreasonable assumptions about init system:

https://github.com/ZoneMinder/zoneminder/blob/master/scripts/zmpkg.pl.in#L359-L362

_rkt_ containers use systemd-nspawn and systemd wrapper to control processes so PID1 inside container is systemd even though systemd is not an init system - there is no _dbus_, no _PolicyKit_, etc.

I've managed to start ZoneMinder only after patching `systemdRunning` to `return 0;` in `zmpkg.pl`.

IMHO daemon should not detect init system at all as it is unnecessary, needlessly complicated, prone to errors, etc.

It feels weird when init script calls daemon script that erroneously detect init system then tries to do something inappropriate to init system... Daemon should not bypass/override or escape from how it is started by init script.

I think we have a good room for improvements to how daemon is starting.

I think we should detect _services_ instead of init systems. The less assumptions are made the better.

**Comment by knight-of-ni** [comment]
Yeah, I agree. I don't like how zm currently tries to detect the init system it is running in (and runs itself in a loop with the help of polkit to make systemd happy), but a distro agnostic way of doing this has escaped me. Others have expressed criticism as well, but none have proposed an alternative that doesn't cause breakage for one or more environments.

I am not sure it is possible to make this work without making some kind of assumption. The current assumption is the name of systemd. What you are proposing has to make assumptions on what a service looks like, and how do you do that if you can't assume a name? If you could be more specific as to what you had in mind, we could certainly explore the possibility. The only condition is that is has to work for everyone, including *BSD's.

What originally drove this is the requirement that, in order to restart a service in a systemd environment, you have to let systemd do it. You can't restart the executable manually from the commandline for example, because systemd does not pick up on the new pid. It then marks the service as failed.  If we could dig a little deeper into systemd and find a way to force systemd to accept the new pid, then this would be the ideal solution.
