### ISSUE TITLE
Unknown function call Storage->Id from /usr/share/zoneminder/www/skins/classic/includes/functions.php:359

### ISSUE THREAD

**Issue by howlett** [ZoneMinder/zoneminder#2209]
This is a ubuntu package from http://ppa.launchpad.net/iconnor/zoneminder-master/ubuntu bionic

Log is flooded with:

```
Unknown function call Storage->Id from /usr/share/zoneminder/www/skins/classic/includes/functions.php:359
```

# zmaudit.pl -v
1.32.0

This is the line:
    $title = human_filesize($S->disk_used_space()) . ' of ' . human_filesize($S->disk_total_space()). 
      ( ( $S->disk_used_space() != $S->event_disk_space() ) ? ' ' .human_filesize($S->event_disk_space()) . ' used by events' : '' );

Commenting out this line stops the flood and allows zoneminder to run more efficiently.

**Comment by mtfurlan** [comment]
In `/www/includes/Storage.php` around [line 190](https://github.com/ZoneMinder/zoneminder/blob/master/web/includes/Storage.php#L190) is what's actually making the error, `event_disk_space`
Should that function use `$this->Id()` or `$this->{'Id'}`?
Because the latter exists elsewhere in that file, and doesn't throw errors.
