### ISSUE TITLE
ZM 1.32 Pre-Event Image Count messes with event MP4 timing

### ISSUE THREAD

**Issue by LNFWebsite** [ZoneMinder/zoneminder#2361]
**Describe Your Environment**
ZM 1.32.3
Ubuntu 18.04 LTS

**Describe the bug**
Setting a pre-event image count causes event videos (MP4) to have erroneous timing. Something to do with the image delta having negative values.

**To Reproduce**
1. Go to Source
2. Click on Buffers
3. Set Pre Event Image Count to a value (yes, less than half the image ring buffer)
4. Force an event and view video timing

**Expected behavior**
Events should terminate at the right time. Ex. 0:15 second long video for 0:15 second long event. Instead, event video files seem to be corrupted by incorrect timing (ex. 0:01 - 169991:01). (BTW, this mp4 method of storing events is a huge improvement, kudos!)

**Debug Logs**
At full verbosity there are no error messages.

Thanks!

**Comment by zm-user** [comment]
I also see this with ZM 1.32.3 on Centos (7.6.1810), seemingly with either of the X264 encode or H264 passthrough options... 

Interestingly the resulting mp4's seem to play ok in the zm console, albeit with incorrect length, but when I try playing with VLC on my desktop it shows only the first frame with no change in the image as the file plays..

**Comment by connortechnology** [comment]
Can you verify this is still an issue with current master?  I have rewritten a lot since 1.32.3 and we are nearing release of 1.34.

**Comment by benoit34000** [comment]
Hi, 
I'm using now release 1.32.3, and it's a great big up since my previous release I used, 1.30.4. Very good job. Recording videos instead of pictures is also a great step ahead !

I'm in front a the same issue as mentionned in the first post.

An event of 42 frames, with a mp4 file of 3MB, is showed in the player with a size of 3579 hours...., and is stalled to the snapshot (I suppose)
Storage is local

It happened when I add a pre-event alarm  to more than 0 (to be able to set alarm frame count more than 1 (I saw a bug regarding this issue, and it was recommended to set a pre-alarm value).
I'm having issue with a 1080p and a 720p ipcam, but I did not notice issue with my 480p ipcam...
(180p and 720p was ONVIF setup, 480p is manual setup)

Here are my buffers params for all my ipcam :
frames 20
warmup 0
pre event 1
post event 5
stream replay 0
alarm frame count 2
 
Hope you will find the bug, cause 1.32.3 is really great (compare to previous release for several years (I really appreciate video recording instead of frame-by-frame only. directories where videos are stored is also a big way more friendly).

Well, keep up the really good job !

Benoit.

**Comment by benoit34000** [comment]
And just an addon to my message.
mp4 video file is correct size and video playing.
It's only through the zm web monitoring the issue appears.

**Comment by benoit34000** [comment]
It seems  the issue did not appear on my side if I'm using h264 passthrough  instead of x264 encoding... Need to let time to validate this.

**Comment by connortechnology** [comment]
Storage of audio can really screw up video length.  This is something that I think I have fixed.  I will need you to update to 1.33.14 to see if the issue is still present.

**Comment by benoit34000** [comment]
Hi,
thanks for your response.
I'm currently testing 1.33.14 side by side with 1.32.3 (in prod)
For both release, it seems the bug is present if I choose x265 encode, and if I choose h264 camera passthrough, it seems everything is fine.
Let me few days more to validate this
Regards,

**Comment by benoit34000** [comment]
Hi,
regarding events of this night, I can confirm bug still exist in 1.33.14 with x265 encode.
And I can also say h264 camera passthrough is working fine, even with 1.32.3.
I will try to desactivate sound recording to check if it's different (I don't need sound, anyways)

**Comment by benoit34000** [comment]
Well, it seems I face same issue on some of the records even with sound disabled from the camera... sorry...

**Comment by benoit34000** [comment]
A quick check, in 1000 events, 25 videos had time issues....
It was mainly very small events (less than 1 second). Maybe the bug appears if the video is very small ?

**Comment by connortechnology** [comment]
Can you see if #2768 Has fixed this issue?

**Comment by connortechnology** [comment]
It is believed this issue was fixed a long time ago and is not present in the 1.34 series.
