### ISSUE TITLE
Deleting multiple events from the event-view, only the last event is deleted

### ISSUE THREAD

**Issue by marcschh** [ZoneMinder/zoneminder#2384]
**Describe Your Environment**
- Version of ZoneMinder [release version, development version, or commit]
1.32.3
- How you installed ZoneMinder [e.g. PPA, RPMFusion, from-source, etc]
PPA
- Full name and version of OS
ubuntu server 18.04

**If the issue concerns a camera**
- Make and Model
- frame rate
- resolution
- ZoneMinder Source Type:

**Describe the bug**
If you watch an captured video and click on "DELETE" than you will see the next captured video from the list. This is fine. But if you delete multiple events on this way, after finishing (by clicking "back" in the upper right corner. But I think it does not matter which way you get out of the event view) and get back to the event-list you will see that all videos are still there expect the last one you deleted.

**To Reproduce**

**Expected behavior**

**Debug Logs**
```

<insert debug logs here, please make sure they are within the ``` quotes so they are formatted properly>

```

**Comment by mnoorenberghe** [comment]
I believe this is caused by https://github.com/ZoneMinder/zoneminder/commit/9ec415b30a0d996381c61b76b828342e651a0196#diff-c594902fd3897e5ff750c632a30a7b8cR413 since the deletion request is an async XHR but then we immediately navigate away from the page before the deletion request has been sent. If I use the debugger things work fine because the XHR has time to run before the `location.replace` but if I run normally I never even see the XHR being made in the devtools network panel.
