### ISSUE TITLE
mp4v2 is obsolete

### ISSUE THREAD

**Issue by onlyjob** [ZoneMinder/zoneminder#2516]
mp4v2 [has been removed from Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=921127):

> mp4v2 is dead upstream and better alternatives exist.

**Comment by SteveGilvarry** [comment]
@connortechnology What do you think? Swap this over to ffmpeg?

**Comment by mastertheknife** [comment]
I don't think we should remove the X264:MP4V2 encoder. Me and others are using it, so far without issues.
The VideoWriter class is an abstract class, it was designed that way so more video writers can be added over time.
In the past i also planned to add x265 because i abandoned it because lack of time, and high encoding CPU usage.

If anything, i think we should implement ffmpeg:ffmpeg video writer. What i mean is use ffmpeg for encoding (take advantage of hw acceleration) and also ffmpeg for muxing the frames into a mp4 file.

**Comment by jwtoler** [comment]
How can we install mp4v2 in Debian Stretch? I have installed everything related to a google search for mp4v2. I keep getting "fatal error mp4.h no such file or directory" error when trying to build from source using the docker method.

**Comment by connortechnology** [comment]
You need libmp4v2-dev

**Comment by sscraggles** [comment]
getting "fatal error mp4.h no such file or directory" when using the docker build of latest commit.  I see the dsc file is installing libmp4v2-dev.

**Comment by EtoTen** [comment]
This affects Ubuntu 19.04 Disco, as mp4v2 is not available via the repositories.

**Comment by kc2zgu** [comment]
Switching this to ffmpeg would allow using other containers, which could potentially lift the restriction of not being able to view video events as they're being recorded (MP4 is somewhat unique among containers in that it doesn't allow live streaming)

**Comment by connortechnology** [comment]
Since 1.35.17 we have removed the mp4v2 code and depenency.
