### ISSUE TITLE
zmcontrol: ONVIF module does not support ONVIF protocol

### ISSUE THREAD

**Issue by redaco** [ZoneMinder/zoneminder#2593]
To control an ONVIF camera, the `Netcat ONVIF` module must be used because the module called `ONVIF` does not use the ONVIF protocol.

Suggested solutions :
1. If anyone knows for which model of camera is intended the `ONVIF` module, rename this module. And then rename the `Netcat ONVIF` module to `ONVIF`.
  * Advantage: things are named correctly.
  * Disadvantage: Users of these modules must change their configuration.
2. Do not touch the current modules and create a new module called `Generic ONVIF` from `Netcat ONVIF`.
  * Advantage: No configuration changes for users.
  * Disadvantage: There is always an `ONVIF` module that does not use the ONVIF protocol.

What do you think ?

**Comment by knight-of-ni** [comment]
Yes, this is known. The onvif control script won't work with any camera, onvif or not. It was never finished by the original author. It got snuck into the project when the onvif probe was added via a very large pr. It's not as simple as just deleting it from the project. It would still remain in every production system out there... and writing sql to remove it automatically runs the risk of deleting someone's custom script with the same name.

The Netcat module on the other hand, was written specifically for one camera, my Netcat camera, which I just threw away due to streaming and/or power issues. I just didn't care to troubleshoot it anymore. I will be the first to tell you the script was poorly written. Because it uses (mostly) static templates for sending commands, it was never intended to work with any other make/model of camera.

The ideal solution to all of this is to write a new control script that sends SOAP messages to the camera, much like the onvif probe, and learns what the real PTZ commands should be. We want to give the script the same name as the current onvif script.

All this takes is for someone to come along and spend some time investigating this further. Are you that person?
