### ISSUE TITLE
MaterialIcons-Regular

### ISSUE THREAD

**Issue by milefork** [ZoneMinder/zoneminder#2652]
**Describe Your Environment**
- Version of ZoneMinder development (Master branch) 2470c09b20f82b05aa0515da1b0e5c44bef32523
- Dockerfile dev version
- Chrome

**Describe the bug**
404 /skins/classic/css/fonts/MaterialIcons-Regular.woff2

and others not found.

File: https://github.com/ZoneMinder/zoneminder/blob/2470c09b20f82b05aa0515da1b0e5c44bef32523/web/skins/classic/css/base/skin.css#L31

Refs this.

**Expected behavior**
Skins loaded

**Comment by connortechnology** [comment]
The url is correct, something else is wrong.  All css and static javascript gets linked into cache dir that is designed for cache busting purposes. (So when file changes, link changes so that we can cache these files but if they change we get an updated url and hence a non-cached version of the file).

So the link to the css will be something like /zm/cache/blablah_base_skin.css
and so ../fonts would give us /zm/fonts/MaterialIcons-Regular.woff2

Normally the /cache is an alias in the apache config pointing to somewhere like /var/cache/zoneminder/cache

So check that.   This isn't a bug in ZM.  it is a misconfig.
