### ISSUE TITLE
Fix fedora/rhel/centos instructions

### ISSUE THREAD

**Issue by fusionstream** [ZoneMinder/zoneminder#3018]
**Setup**
- Zoneminder 1.32.3-1.fc29
- Installed via RPMFusion
- Fedora 29

**Issues**
2 issues here:
1) The install instructions do not note the difference between zoneminder-apache and zoneminder-nginx. Installing the former will cause your entire /var/www dir to change ownership. It would be better to document it as ```dnf install zoneminder-nginx``` or at least to note the difference.
2) fcgiwrap is installed but spawn-fcgi is not. There is no daemon with fcgiwrap on Fedora.

**To Reproduce**
1) ```dnf install zoneminder```
2) Follow the readme-nginx instructions

**Expected behavior**
I expected that when I follow the instructions to the letter, it will immediately result in a working configuration.

**Solution**
1) To solve the problem for point one, one has to install zoneminder-nginx
2) To solve the problem for point two, one has to additionally run

   1) ```dnf install spawn-fcgi```
   2) Edit /etc/sysconfig/spawn-fcgi and fill it with 
       ```
         FCGI_SOCKET=/run/fcgiwrap.sock
         FCGI_PROGRAM=/usr/sbin/fcgiwrap
         FCGI_USER=nginx
         FCGI_GROUP=nginx
         FCGI_EXTRA_OPTIONS="-M 0700"
         OPTIONS="-u $FCGI_USER -g $FCGI_GROUP -s $FCGI_SOCKET -S $FCGI_EXTRA_OPTIONS -F 1 -P /var/run/spawn-fcgi.pid -- $FCGI_PROGRAM"
         ``` 
       where the path for the sock file is modified so that it matches with the default config provided by zoneminder-nginx

   3) ```systemctl enable spawn-fcgi```
   4) ```systemctl start spawn-fcgi```

**Comment by knight-of-ni** [comment]
It's been a while since I last run in this configuration, and my memory is coming back to me. The fcgiwrap package is what handles spawning fcgi automatically. As long as fcgiwrap@nginx.socket is enabled, it will auto-spawn fcgiwrap@nginx.service, which in turn starts fcgi.

**Comment by fusionstream** [comment]
Hmm. I missed the @nginx part. I haven't used any fcgi in ages either. 

In any case, the fcgi part does not work out of the box. Or so it seems.

Will do a bit more research, update here, then do a pr.

For point 1, installing _zoneminder-httpd_ and thus _httpd_ really really messed with my file perms. It may be low priority but it's fairly high impact. But I'll do the pr.

**Comment by knight-of-ni** [comment]
Yes, switching from -httpd to -nginx subpackages is likely what caused all this. 

The root problem is that, unlike Debian distros, Redhat uses a different user account for each different web server. Since Zoneminder runs under the user account of the web server, all writable areas have to be owned by the same web account user... so if you switch from httpd to nginx, then all files/folders have to change ownership from httpd to nginx, **including the php session files and folders**. <- this one is sneaky.

UPDATE: Looks like I had previously figured out that adding nginx user to the apache group solves the inability to write a php session:
https://github.com/ZoneMinder/zoneminder/blob/master/distros/redhat/zoneminder.spec#L284

ZoneMinder doesn't touch /var/www folder, however. That change was probably done by the httpd/nginx packages themselves.
Look here to see what files & folders are changed: https://github.com/ZoneMinder/zoneminder/blob/master/distros/redhat/zoneminder.spec#L286

The zoneminder package also does not know about additional zm storage areas. Those will have to be fixed by hand.

No matter how one slices it, changing web servers is very problematic for any application. If zoneminder didn't change the permissions of the files & folders it needed to write to, you would still have a non-functional system and would still be here in this forum, just asking different questions.

I also get you might not be here at all if our documentation was up to date. You have my apologies for that.

I am the package maintainer for fcgi and fcgiwrap and have set the unit files in the fcgiwrap package as user instantiated. It's pretty straightforward, but if you want to see how to set it up in the general sense (shouldn't have to for zoneminder - see below), you can read about it here: /usr/share/doc/fcgiwrap/SETUP

I also added drop in config unit files in the zoneminder package that require fcgiwrap to be started in order to start zoneminder:
https://github.com/ZoneMinder/zoneminder/blob/master/distros/redhat/nginx/zm-nginx.conf

Unless this file is missing on your filesystem, zoneminder should not even start if fcgwrap, and fcgi in turn, is not already up and running.

Up until last December, I was running zoneminder-nginx on f29 on a raspi 3. I know it works. It's possible I missed something in the documentation to make this all work right out of the box, but figuring that out would require having an environment to match, which I don't have at the moment. Not saying I'm not going to do it, but I can't make this a priority.

I get it. This is important to you, but everything I'm working on is important to somebody. I am not humanly able to solve everyone's problems in a timely manner, and I've got to make decisions as to how to use my spare time wisely. Documentation is something that anyone can do, not just the few who write the code. Keeping the documentation up to date is a full time job, and it would be a big help if someone would step up and volunteer.

Once you are through all this, I'd love to convince you to upgrade to f32. We only support the two latest major releases of anything, which is why rpmfusion f29 repo doesn't have the latest zoneminder release. Alternatively, you can build your own f29 zm packages using mock or our docker based build system.

**Comment by fusionstream** [comment]
Mate. Not to fret. Not blaming you or anything. Here's a smiley. :-)

Yea the www-data account is one of the few things I like about ubuntu.

f29 on a pi3? I haven't been keeping up it seems. f32 on the server? I definitely haven't been keeping up! hah!

I'll take a look at the unit file. I had a look at fcgiwrap@nginx while I was writing my previous message and it seems to be running via indirect and it's filled with document root errors so I'll have to do read up on this. Long time since I ran fcgiwrap.

I'll try the upgrade to f32 first. Who knows it may have fixed the problem. It wouldn't make too much sense to fix something that isn't supported. As a small aside, might I suggest you increase that support level to 3 majors. 2 majors on Fedora is only about a year.

If the upgrade goes swimmingly, I won't need to do any PR. Otherwise, I'll do the PR.

**Comment by tgreer** [comment]
Just wanted to mention, running on Centos8 and similar dilema here. Using ngin,
nginx log shows: *2293 connect() to unix:/run/fcgiwrap/fcgiwrap-nginx.sock failed (2: No such file or directory)
Zoneminder version: v1.34.20

Any pointers?

**Comment by knight-of-ni** [comment]
I had a moment of opportunity and put fedora back on one of my raspberry pi's.

Based on that experience, I made the following changes:
- 80afbbd9ce5a10c9d1fabebd036445d4e4b421d2 fixes a problem in the rpm specfile, auto generating the self signed cert
- 96ade2f9d08120cf28fbdc9fb283ba1ce3efe8f7 updates the nginx readme, to include the step: `sudo systemctl enable --now fcgiwrap@nginx.socket`. This missing step was likely what caused the issue you were experiencing.
- I've updated our readthedocs to describe the two different workflows, depending on your choice of web server:
https://zoneminder.readthedocs.io/en/latest/installationguide/redhat.html
