### ISSUE TITLE
Time to next event at 50 years

### ISSUE THREAD

**Issue by connortechnology** [ZoneMinder/zoneminder#3052]
Many people have reported this and I've seen it too. Not sure how to reproduce exactly.

**Comment by linuxbox01** [comment]
I'm at a loss as well.  Thought perhaps we did an upgrade wrong, so uninstalled, wiped db, new installation from rpmfusion 1.34.20.  Same issue.....
Installed from docker image 1.34.18, setup four cameras, working perfect for a day.  Only things that wouldn't work was the rewind in the event view, and the speed dropdown didn't work properly, sometimes had to refresh the page if FF, or the dropdown was selected, but that's not a huge deal for us.  Added in 6 more cameras, left for a day, now the issue is showing up all the time....  We can pan ahead in the event view, but we've never been able to click more than 5 times before the problem shows up.  Sometimes on the first click, sometimes after a few,  but it is persistent.  I can give you access to the system if you have any ideas, or if you want me to try something, or provide any other info, let me know.  I can't seem to find anything in the logs that would indicate any problems.

**Comment by joedaimarg** [comment]
Same issue encountered here. I'm using the docker version. Worst on the latest update was, I'm getting this screen when trying to rewind an event.

**Comment by connortechnology** [comment]
Fixed in 061c88939429d53d0f8565c110290c4aaca989e3

**Comment by connortechnology** [comment]
Fixed in released 1.34.22
