### ISSUE TITLE
Compile issues for development on FreeBSD

### ISSUE THREAD

**Issue by y2kbadbug** [ZoneMinder/zoneminder#3165]
**Environment**
Version: 1.35.18 commit 0dc748acb
Compiled from source into package
FreeBSD 12.2-STABLE

**Bug**
Unable to compile the development version of ZoneMinder on FreeBSD due to missing headers as well as an issue with zm_eventstream.cpp

Several files files failed to build due to missing headers

Header missing was `#include <errno.h>` which created this error message:
```
error: use of undeclared identifier 'errno'
        Error("Can't glob '%s': %s", glob_pattern, strerror(errno));
```

I was able to correct it on my system with these patches:
```
--- src/zm_comms.h.orig 2021-02-16 23:10:34 UTC
+++ src/zm_comms.h
@@ -29,6 +29,7 @@
 #include <vector>

 #if defined(BSD)
+#include <errno.h>
 #include <sys/socket.h>
 #include <netinet/in.h>
 #endif
--- src/zm_config.h.orig        2021-02-16 23:12:32 UTC
+++ src/zm_config.h
@@ -23,6 +23,7 @@
 #include "config.h"
 #include "zm_config_data.h"
 #include "zm_config_defines.h"
+#include <errno.h>
 #include <string>

 #if !defined(PATH_MAX)
```
I can provide the actual files that generated the errors if needed.

Errors also were generated due to the missing header `#include <sys/socket.h>` for the files `src/zm_monitorstream.h` and `src/zm_remote_camera.h`.  It specified an undeclared identifier of `sockaddr` and `MSG_DONTWAIT`.

I use these patches to correct this problem:
```
--- src/zm_monitorstream.h.orig 2021-02-16 23:42:54 UTC
+++ src/zm_monitorstream.h
@@ -21,6 +21,7 @@
 #define ZM_MONITORSTREAM_H

 #include "zm_stream.h"
+#include <sys/socket.h>
 #include <sys/time.h>

 class MonitorStream : public StreamBase {
--- src/zm_remote_camera.h.orig 2021-02-16 23:56:07 UTC
+++ src/zm_remote_camera.h
@@ -23,6 +23,7 @@
 #include "zm_camera.h"
 #include "zm_rtsp_auth.h"
 #include <string>
+#include <sys/socket.h>

 #define SOCKET_BUF_SIZE 8192

```

Also had a missing header of `#include <pthread.h>` in `src/zm_mpeg.h`:
```
--- src/zm_mpeg.h.orig  2021-02-16 23:52:07 UTC
+++ src/zm_mpeg.h
@@ -21,6 +21,7 @@
 #define ZM_MPEG_H

 #include "zm_ffmpeg.h"
+#include <pthread.h>

 #if HAVE_LIBAVCODEC
```

and `#include <sys/types.h>` in `src/zm_thread.h`:
```
--- src/zm_thread.h.orig        2021-02-16 23:42:12 UTC
+++ src/zm_thread.h
@@ -32,6 +32,7 @@

 #ifdef __FreeBSD__
 #include <sys/thr.h>
+#include <sys/types.h>
 #endif

 class ThreadException : public Exception {
```

Finally, there was an issue with `src/zm_eventstream.cpp` on line 351, which with assistance was corrected with this page:
```
--- src/zm_eventstream.cpp.orig 2021-02-16 23:33:52 UTC
+++ src/zm_eventstream.cpp
@@ -348,7 +348,7 @@ void EventStream::processCommand(const CmdMsg *msg) {
           curr_frame_id = 1;
         } else {
           Debug(1, "mode is %s, current frame is %ld, frame count is %ld, last frame id is %ld",
-              StreamMode_Strings[(int)mode], curr_frame_id, event_data->frame_count );
+              StreamMode_Strings[(int)mode].c_str(), curr_frame_id, event_data->frame_count );
         }

         replay_rate = ZM_RATE_BASE;
```
The issue was 
```
/src/zm_eventstream.cpp:351:15: error: cannot pass object of non-trivial type 'const std::string' (aka 'const basic_string<char, char_traits<char>, allocator<char> >') through variadic method; call will abort at runtime [-Wnon-pod-varargs]
              StreamMode_Strings[(int)mode], curr_frame_id, event_data->frame_count );
```

I don't know C enough to really explain the problem, the person who assisted me provided the correction of adding c.str().  I can provide more details if requested.

I hope this is enough information to assist in resolving these issues, please let me know if there anything else I can provide or do to help.

Thanks!

Tagging @adriaandegroot as they are the person who assisted me in resolving these issues.

**Comment by adriaandegroot** [comment]
This would be easier on the ZoneMinder folks as a PR, but the necessary patches are all here. FreeBSD uses clang / llvm (which as a compiler is sometimes more picky than gcc) and has its own BSD libc (which is more conservative than GNU libc). So that leads to a common situation where headers that GNU libc pulls in implicitly (like `errno.h`) need to be added explicitly for FreeBSD. There's generally no need to `#ifdef` them, since they're POSIX headers and needed *anyway*.

Weirder is the patch to `src/zm_eventstream.cpp`. What we're seeing there is that a `std::string` **object** is being passed as a parameter (after a couple of rounds of macro expansion) to the variadic function `logPrint()`; the printf-style format is going to consume that as a `char *` I suppose, and I would **expect** things to blow up at that point if it's ever called. Adding the `.c_str()` gets a `char *` to the actual C-style-string data, which makes it compile again.

I'm informed by @y2kbadbug that the code in `src/zm_eventstream.cpp` previously was a ternary expression with C-string literals, so this may have just slipped in recently.
