### ISSUE TITLE
ERR: Can't insert frame: Out of range value for column 'Score' at row 1

### ISSUE THREAD

**Issue by defendertx** [ZoneMinder/ZoneMinder#319]
I'm using ZoneMinder to capture an mjpeg stream from an ITS camera. My company has been using ZoneMinder for years with OpenSUSE 11.4 with great success, but I'm trying to move to OpenSUSE 13.1.

I just setup a brand new OpenSUSE 13.1 machine (physical machine, not VM) and installed ZM from the repo (version 1.26.4). It's running in conjunction with MariaDB 5.5.33.

When I tried to add my camera, I am receiving an error from zma "Can't insert frame: Out of range value for column 'Score' at row 1". This is from /src/zm_event.cpp line 568.

The schema in MariaDB shows the following for column Score in table Frames:

Field | Type | Null | Key | Default | Extra
------- | ------- | ----- | ------- | --------- | --------
Score | smallint(5) unsigned | NO | | 0 |

Could you offer any assistance here? Have I configured something improperly? I would love to get this running with OpenSUSE 13.1 since it was just picked up by Evergreen and we are moving our servers in that direction.

Thanks!

**Comment by knnniggett** [comment]
Steps to Reproduce
-------------------------
It took a while to figure this out, but here are the steps to duplicate this issue:
- Run your dB engine with strict mode on (newer versions of mysql/mariadb ship with this turned on)
- Set any camera to Record or MoRecord

If either of these are not true, the error will not manifest itself. 

Background
----------------
This link sums up was it happening perfectly:
http://www.tocker.ca/2014/01/14/making-strict-sql_mode-the-default.html

The logic in zm_event.cpp has indeed been attempting to write a value of "-1" to the score dB column.  However, due to a "feature" of mysql, the dB engine would automagically translate a "-1" to "0" when trying to stuff the value into a field of type unsigned int, without so much as giving a warning.  The refereed link describes this perfectly.  This, in effect, covered up a bug that has been there since day one.

Workaround
----------------
The immediate workaround is to set `sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES` in your mysql config as @newburns previously pointed out (thanks for discovering this). 

Note that changing the field type to a signed int is not the recommended way to fix this.  The Score, as written to the database, should always be >= 0.

Permanent Fix
-------------------
PR #1016 fixes this permanently by resetting score to 0 if it is less than 0.

I would not be surprised if there are other parts of ZoneMinder that develop the same kind of problem.
