### ISSUE TITLE
js error in watch

### ISSUE THREAD

**Issue by connortechnology** [ZoneMinder/zoneminder#4076]
web_php[1580141]: 06/12/2024 04:51:20 PM.896432 web_js[1580141].ERR [10.120.1.36] [Uncaught%20TypeError%3A%20Cannot%20read%20properties%20of%20null%20(reading%20'indexOf')] at cache/skins_classic_views_js_watch-VueIP-1718129168.js line 627

This happens when you click anywhere not in the video...

I believe this is due to the handleClick being attached to the document around 1190
document.addEventListener('click', function(event) {
    handleClick(event);
  });

I'm going to push a fix to stop the errors, but perhaps a review of what to do when we aren't clicking on something relevant needs to be done.

**Comment by IgorA100** [comment]
This is very strange because:
1. This error does not appear for me.
2. "handleClick" only processes if:
- click on "#nav-link" (switch between cameras) or
- click on any element inside "#dvrControls" (DVR control panel)
- click on any element inside "#wrapperMonitor" (the image itself)

Because there is a condition
```
 } else if (!event.target.closest('#wrapperMonitor')) {
 return;
```
then when you click on an arbitrary place to the line with the condition
`if (panZoomEnabled)`
The code should not be executed.
