### ISSUE TITLE
GridStack slow to init when a lot of monitors on montage

### ISSUE THREAD

**Issue by connortechnology** [ZoneMinder/zoneminder#4127]
With over 70 monitors, it can take over 40 seconds before first render.  firefox will complain about gridstack init slowing down the browser, etc.

I notice that we are calling init twice, which could perhaps be improved.  Not sure what else can be done.

**Comment by IgorA100** [comment]
I'll definitely watch it, but later.
I don't have time right now :(

**Comment by IgorA100** [comment]
> With over 70 monitors, it can take over 40 seconds before first render

1. Can you make a video of the whole rendering process?
2. Does the rendering speed depend on the selected "Layout"? I think "8Wide" will load faster than "3Wide"

**Comment by connortechnology** [comment]
https://github.com/user-attachments/assets/4ecf6c90-9580-4ede-af1c-857b46ea22aa

**Comment by connortechnology** [comment]
Yeah 8 Wide is faster.

**Comment by IgorA100** [comment]
> I notice that we are calling init twice

GridStack initialization consumes almost no resources. Yes, when opening a page, initialization occurs twice, this is normal for now.

Thanks for the video.

As far as I understand, the long page rendering occurs due to loading a large amount of information.
Reducing "Stream quality" to -50 should speed up page rendering.

**Comment by IgorA100** [comment]
Maybe I found the reason.

**Comment by connortechnology** [comment]
It is massively improved, while faster would be even better, I think we can close this.
