### ISSUE TITLE
Store events in mp4 container

### ISSUE THREAD

**Issue by knnniggett** [ZoneMinder/ZoneMinder#452]
this is a placeholder for dicussion of mp4 container storage in the video branch

**Comment by seeebek** [comment]
Do you have a TODO list for this feature? What is already done? What is still needed to consider this feature completed enough? What are the priorities? I would like to help but I'm not sure where to start.

**Comment by knnniggett** [comment]
@seeebek See issue #39 
Originally, there were two competing methods in different branches, one using mp4 and the other mkv container.  However, the best of both branches are now being used and are found in the feature-h264-feature branch.  We'd have to get @SteveGilvarry to chime and tell us what specifically you could help with.  I'm pretty sure he has hit a snag for the time being, but I don't recall what it was.

**Comment by seeebek** [comment]
I went throug all issue threads concerning mp4 and mkv event containers. It looked like you have the mp4 containers working already and you were working on the client side to display the events with the html5 video tag. I'm probably missing something as it sounds like the goal is almost reached. I will compile the feature-h264 branch this weekend and see what might be missing. It would be still nice if @SteveGilvarry could point me in the right direction.

**Comment by knnniggett** [comment]
Yes, the core of the mp4 branch does work.  However, it still transcodes the native stream from the camera before writing it to disk, which means this method is just as cpu-inefficient as zoneminder is today.  

The H264 branch did not do that and from what I understand is much more efficient.  @SteveGilvarry reached a point in his development where he realized the mp4 container is natively supported in virtually all modern browsers, but the mkv container was not.  Thus he merged the best features from both branches.  The result is currently in the feature-h264-videostorage branch.

**Comment by connortechnology** [comment]
Having played with the H264 branch, it currently has issues compiling on ubuntu.

I made it compile on 15.04 but it crashes.  It also does not compile on trusty but that may be due to my changes to make it work on 15.04.  As usual libav is really being a problem.

**Comment by SteveGilvarry** [comment]
Yes I need to get onto 15.04 to check it out, had some issues with Parallels supporting it, will check again now. But from what I saw it was just typical issues with ffmpeg/libav.
On older versions on ubuntu it is working fine, but issues list is as follows.
1. h264 passthrough is grabbing first keyframe after event, needs to buffer the previous keyframe as a minimum, and probably respect the settings for pre-event frames to capture. Issues between ZM wanting to work in frames and getting video to slice on keyframes, might need to ensure we always take more video than frames that ZM wants and know how many frames between keyframe and first ZM frame. My C fu is not good enough to get this sorted, have some ideas but memory management side bewilders me. Was working on it when I got busy with some renovations, but might have time this weekend.
2. Event Playback Swapped to videojs player for event playback, seems to work fine, could have some refinement of controls and add frame by frame playback. There is a PR with some extra stuff for this, I need to get back to it to check that and get it merged. This included the ability to click on a frame number in ZM interface and get that frame extracted from the video, but issues above with keyframes means frame and time don't line up.
3. Timeline Playback was originally fixed with a html5 playback option, need to check it again.

**Comment by seeebek** [comment]
The H264 branch is not compiling on 14.04 because of libav. Specifically avformat_alloc_output_context2 causes problems. Which is funny because there is this:

#if LIBAVCODEC_VERSION_MAJOR < 54
#define avformat_alloc_output_context2(x,y,z,a) hacked_up_context2_for_older_ffmpeg(x,y,z,a)
#define av_err2str(x) ""

Which probably means that the libav in 14.04 is older version listed as 54. I'm not sure about that.
I will try to get it run on 15.04 since it has newer libav.

@SteveGilvarry 
1. This is exactly what needs to be done but I think it is more important to get it working as is. Even if it ignores pre-event frames. It is easier to do it step by step and add this functionality later. And it would be easier to understand what is the current state (for a beginner like me).
2. I thought about the problem of frame by frame progression. The only solution is to map frames to time (something like 1-0:00.01; 2-0:00.24). This way you can get the videojs player to make frame by frame steps(even backwards). I think I might be capable to do it (I hope).

I will spend some of my free time for the next few weeks and see if I can help you with the tasks. It would be great if it worked out. Additionally I have few other feature ideas but those have lower priority.

**Comment by connortechnology** [comment]
I have a PR that handles the libav issues and allows it to compile on 15.04. I'll try to get it in here today.

**Comment by SteveGilvarry** [comment]
@seeebek I run on 14.04 but with latest ffmpeg.

**Comment by knnniggett** [comment]
@SteveGilvarry has merged the best of the mp4 branch into the mkv container branch.  I'm closing this issue since it is no longer relevant.  Discussion about his work should be held in #39 .
