### ISSUE TITLE
ZM_DIR_EVENTS and ZM_DIR_IMAGES not secure, cannot be moved etc

### ISSUE THREAD

**Issue by SteveGilvarry** [ZoneMinder/zoneminder#601]
So I started out looking at the Debian package and found some rules deleting symlinks and recreating them, and there was a note about it being a kludge and hopefully would be addressed upstream. I started to look into them and here is a summary of issues I have found.
1. Correct location for this content is /var/lib/zoneminder (Cmake distros seem to have that right)
2. Folders must be under web root to work.
3. All distributions do some sort of symlink from actual file location to web root
4. Files in Events and Images are accessible always to web. Somewhere I saw a comment about this in a package, cannot for the life of me find it again.

Anyway it got me thinking first we need some sort of page to serve all content requests, so that we can hide the actual contents of events and images from unauthorised users.
Doing that then allows us to remove the need for symlinks as the request will go and find the folder and bring the content back.
That should then allow ZM_DIR_EVENT and ZM_DIR_IMAGES to point to /var/lib/zoneminder or any other physical location that someone wants?
Also need to do something to detect any moved content and prevent audit from deleting it.
##

**Comment by knnniggett** [comment]
@pliablepixels just pointed out in our irc channel, and confirmed by @SteveGilvarry , that this is still an issue.  For some reason I thought we fixed this. I simply had not deleted the warning that is still present in the redhat/fedora config file.

With detailed knowledge of how zoneminder stores its jpegs under the events folder, one can craft a url to retrieve any jpeg under the event folder.

It turns out that the zmninja app, the new scrubbing feature (pull request at the moment), and the zonemidner timeline, actually rely on this "feature".  This makes a solution more tricky as it will certainly require changes to these features as well.

**Comment by Linwood-F** [comment]
Just to complete the picture the single frame event viewer also does this under the covers as well.  My guess is this might even be more broadly.

Postscript: As I was writing this I realized the "stills" that scroll individual images in an event also uses this technique.  I think removing it is going to take some hunting.

**Comment by knnniggett** [comment]
For a long time (years?), I have been troubleshooting issues where the user tried to move the events to a different location on the filesystem but failed miserably.  The recommendation was always to keep it under the web root.

Well, due to a somewhat recent conversation in our IRC channel, I was able to successfully move the images folder outside the web root to an arbitrary location, and I did not encounter any issues.  
To my surprise, montiors streamed, events played back, and thumbnails worked.

We should look into this further as it might not require any changes to zoneminder.  If anyone has time, I recommend we build dome packages on various distros with events and images folders outside webroot, and then test.

**Comment by newburns** [comment]
I have always been able to store images outside of root. Granted, I don't move any folders, but I start outside of root.
1. I mount a ~4TB or more array to /storage/zm.
2. Create the 3 folders needed. (Sounds, Images, Events)
3. Change the folders in the config on the web frontend before ever starting Zoneminder.
4. Start Zoneminder service, and everything seems to work as expected.

**Comment by josh4trunks** [comment]
My suggestion is to use XSendfile (apache) or x-accel-redirect (nginx).
* zoneminder would need to know which webserver is passing the request. this can possibly be done by having a header added in the htaccess (apache) or the nginx config.
* disable direct access to the events/images folder in the htaccess (apache) or nginx config.

**benefits**
webserver handles serving the file, faster, less memory then through other means
more secure then the current direct serving of image files

**downsides**
* apache users need to enable xsendfile, and I believe, allow it for any directories outside the webroot
* nginx users would need to setup a location block that...
    * set the header informing zoneminder to use x-accel-redirect
    * set the location as internal
    * add an alias if the events/images location is actually not under the webroot

####

I helped implement/improve this when sendfile was an option in ownCloud. The option has since been removed when file locking become standard in ownCloud (passing the download to the webserver meant PHP no longer new about it and could remove the lock, but file locking ins't an issue with ZM).
It did work, and allowed good performance when serving large files.
We could make this basically transparent for apache users. nginx users would just need the one location block, which would serve a dual purpose of disabling direct access to the events/images.
All users would need to add an extra config line somewhere if they kept their folders somewhere other than the webroot.

**Comment by knnniggett** [comment]
@josh4trunks ZoneMinder already handles this internally without changing the source code. This was discovered about a year ago. I tested this on CentOS for a short period by deleting the symlink to the events folder and changing the path under options to the absolute path to the event files. It worked. The only thing preventing us from repacking zoneminder this way is time and resources. 

If you want to help, fee free to test this idea. It certainly does need further testing.

**Comment by josh4trunks** [comment]
hmm, ok, I'll test this out on nginx to confirm images are viewable with the folder moved.

**Comment by knnniggett** [comment]
Yeah, your idea looks sound if we can make it reasonably compatible with different webservers. We can certainly look into that if the code already in ZoneMinder has some kind of issue. 

We need someone to take the time to thoroughly check all the widgets... live stream, events, thumbnails, montage, timeline, etc. to make sure changing to an absolute path, outside of the webroot, really is that easy. It might not be. One has to wonder why the code was there all along, but not implemented.

There is also the issue of safely migrating the end user from the old way to the new, without losing any events. This might just be a packaging thing.

**Comment by josh4trunks** [comment]
This defintly does work with nginx. =]
The url `/index.php?view=image&path=5/16/04/28/19/40/03/00016-capture.jpg` works, and properly requires authentication.

If we want to use sendfile/x-accel to require authentication, and have increase performance (file serving using webserver vs PHP), I can help implement it.
I wouldn't call myself a dev, but I do have a good understanding of how it worked in ownCloud.

**Comment by josh4trunks** [comment]
The solution to force authentication seems straight forward to me
* disable file access to events/images directory
    - use .htaccess for apache
    - add `deny all` location block in nginx
* remove the logic in functions.php and always `return( '?view=image'.$querySep.'path='.$path );`

We could at a later time add the option to enable x-sendfile / x-accel for admins who want the increased performance.

**Comment by connortechnology** [comment]
I definitely want to remove all direct access to events dir.  I have been working on the image view to have it take event_id and frame_id instead of path.  I don't think the UI should have any real knowledge of fs layout.  I have also been working on improving performance by caching thumbnails and scaled images instead of just generating them spitting them out.

I'm not sure how performance critical this all is, but certainly with putting zm on things like pi's, every little bit helps.  

We appreciate any code you toss our way :)

**Comment by pliablepixels** [comment]
My understanding is @connortechnology already implemented the image redirection logic (I use it for zmNinja) - I was having a conversation with @knackrack615 on IRC today and he brought up this concern of being able to guess image paths. 

So what is the latest on this? Possible to move it out of webroot without any adverse effects? Or is there more work to be done? I think there is still a warning on ZM_DIR_EVENTS help that says don't move it out of web root.

**Comment by josh4trunks** [comment]
my locations are outside of the webroot and they work just fine with v1.30.0

**Comment by knnniggett** [comment]
Yes, it has been known for some time that the core functionality of zoneminder works just fine with the images and events folders outside the webroot. Apparently the logic was implemented years ago. However, no one on the current team knew it at the time.

However, moving to this is not nearly as simple as changing the help text to say "ok you can do it now". If not done properly, many users (read -> nearly everyone who does not understand how zoneminder core works) would lose all their events.

Here is what needs to happen in order to move forward:
1) Someone needs to step up and document, not just the core functionality works, but all the auxillary functions work too. I would not be surprised if things like the timeline, email attqachments, or some other lesser used feature might have issues or won't work at all. We need someone to go through a checklist of zoneminder functions and identify what works and what doesn't.... merely saying "yes I did that" is not sufficient.

2) It would be helpful if someone wrote a distro agnostic set of steps for the average user to make the change on their own. The trick is to do it in a way which won't get undone after a "yum update" or "apt-get update". The place for this would be wiki.zoneminder.com.

3) Update the help text in the master branch to reflect the change in step #2 in a way that does not cause end users to lose events.

4) Package managers must implement step #2 into their packages, either through documentation, a change in the package itself, or a little of both.

**Comment by josh4trunks** [comment]
ahh makes sense. in my case I fresh installed v1.30
