### ISSUE TITLE
Centos 6.5 crashes

### ISSUE THREAD

**Issue by zonepilot** [ZoneMinder/ZoneMinder#619]
I have installed and run Zoneminder under Centos 6.5. It seemingly works fine (with SE-linux off), however after some time it has caused my server to crash. It hangs and keyboard is blinking, and only way to come back up is to hard reboot. On 3 occasions it stopped with this screen-output (see image screen-crash-1) and the latest it showed a screen like image 2.
Could anyone help me finding out what could be the cause of this? 
I  do not have a clue what these trace calls are or how they appear, other than they only started appearing after I installed Zoneminder.
Cheers,
![crash-screen-1](https://cloud.githubusercontent.com/assets/10062324/5282211/8cedf02a-7b04-11e4-9e92-d1b46d790c1e.jpg)
![crash-screen-2](https://cloud.githubusercontent.com/assets/10062324/5282224/ac509166-7b04-11e4-80e9-b17eb36baeba.jpg)

**Comment by lpallard1** [comment]
May be late replying but...

the current over-charge on the usb port may or may not be related to the file write issue you had.  If related then I would check for motherboard shorts with the case, if not then I'd suspect motherboard failure.

If not related, then the file write issue is likely due to dying HDD or bad ram, most likely dying HDD.  I
I literally went through dozens of drives with similar errors.  Basically what you saw is a kernel panic.

First start off by doing a fsck from a boot CD on the drive (on all ext4 partitions) that is likely to be failing.  If fsck fixes some stuff, BACKUP right away.

That reminds me when I had a Slackware server doing the same thing because the mdadm driver was crashing due to HDD failure (WD greens.........) Live n Learn
