### ISSUE TITLE
Feature Request: Face and License Plate detection / Recognition

### ISSUE THREAD

**Issue by whopperg** [ZoneMinder/ZoneMinder#630]
Hi there,

i've tried my way with openbr/vc but i cant get it to work. So i took a look at the web and saw that there actually is a plugin for zm! (http://www.zoneminder.com/wiki/index.php/Third_Party_Patches)

Is this also included in this branch? If so, is there an Tutorial?

Cheers,

**Comment by manupap1** [comment]
Sorry I have not been able to focus on this subject during the past weeks.
I just refreshed my fork of ZoneMinder with the plugin framework: https://github.com/manupap1/ZoneMinder (plugin_support branch)
I am not sending a pull request right now because this stuff depends on https://github.com/ZoneMinder/ZoneMinder/pull/646.
The LPR plugin is there: https://github.com/manupap1/libzoneminder-plugin-openalpr
If you want to test, please follow instructions on the README.md file.

**Comment by connortechnology** [comment]
I'll get onto testing/merging        #646 soon.

**Comment by whopperg** [comment]
@manupap1:

Nice work mate! Loved the documentation! Just cloned your fork and try to install it as i write.

Cheers!

**Comment by whopperg** [comment]
well - i failed. or at least the build:

snip:
make[1]: Entering directory '/downloads/manuapap1/ZoneMinder'
I: zoneminder_1.28.1
dh_install --fail-missing
cp: cannot stat âdebian/tmp/usr/share/perl5/ZoneMinderâ: No such file or directory
dh_install: cp -a debian/tmp/usr/share/perl5/ZoneMinder debian/libzoneminder-perl//usr/share/perl5/ returned exit code 1
debian/rules:80: recipe for target 'override_dh_install' failed
make[1]: *** [override_dh_install] Error 2
make[1]: Leaving directory '/downloads/manuapap1/ZoneMinder'
debian/rules:46: recipe for target 'binary' failed
make: *** [binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
debuild: fatal error at line 1376:
dpkg-buildpackage -rfakeroot -D -us -uc failed

**Comment by manupap1** [comment]
@whopperg 
This should be fixed now.

**Comment by whopperg** [comment]
Thanks mate! Working - after some smaller hickups. Going to build the plugin now. I'll get back to you with more Infos if you want to.

Cheers!

**Comment by whopperg** [comment]
Got another one ;-)

make[1]: Entering directory '/downloads/manuapap1/libzoneminder-plugin-openalpr'
I: libzoneminder-plugin-openalpr_1.0.0
dh_strip --dbg-package=libzoneminder-plugin-openalpr-dbg
make[1]: Leaving directory '/downloads/manuapap1/libzoneminder-plugin-openalpr'
   dh_makeshlibs
   dh_shlibdeps
dpkg-shlibdeps: error: no dependency information found for /usr/local/lib/libopencv_imgproc.so.2.4 (used by debian/libzoneminder-plugin-openalpr/usr/lib/zoneminder/plugins/libzm_plugin_openalpr.so)
Hint: check if the library actually comes from a package.
dh_shlibdeps: dpkg-shlibdeps -Tdebian/libzoneminder-plugin-openalpr.substvars debian/libzoneminder-plugin-openalpr/usr/lib/zoneminder/plugins/libzm_plugin_openalpr.so returned exit code 2
debian/rules:42: recipe for target 'binary' failed
make: *** [binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
debuild: fatal error at line 1376:
dpkg-buildpackage -rfakeroot -D -us -uc failed

**Comment by manupap1** [comment]
It failed because you have a local installation of the libopencv_imgproc library which takes precedence over the package version of the library.
And obviously dpkg-shlibdeps does not find a package dependency for this local library.

Run the following command should point out the problem:
```bash
ldconfig -p | grep libopencv_imgproc.so.2.4
```
Your  options:
- If not in use, remove the local library and retry to build the package,
- Change the path priority in ldconfig and retry to build the package,
- Do not build the package, and simply install with `sudo make install`.

**Comment by whopperg** [comment]
Thanks manupap1 :+1: 
(i've really tried all i could but building packages and stuff isnt really my thing ;-) mostly im a Windows guy : )
 sudo make install did the trick. Plugin is running! I have to wait till my wive is back home to see if it catches the plate ;-)

**Comment by manupap1** [comment]
@whopperg 
If you have some issues about the plugin, thanks to report them on my [repository](https://github.com/manupap1/libzoneminder-plugin-openalpr/issues).

**Comment by whopperg** [comment]
@manupap1:
Thank you very much. I will do that.

Should i keep this request open for face recognition part?

**Comment by manupap1** [comment]
I would say to keep this request open for now.

**Comment by knnniggett** [comment]
Closing this out since it appears that @manupap1 has written a ZoneMinder plugin that does this. 
https://github.com/manupap1/libzoneminder-plugin-openalpr
