### ISSUE TITLE
VideoStream::OpenStream fails in write_header for mp4 and mov

### ISSUE THREAD

**Issue by whorfin** [ZoneMinder/ZoneMinder#756]
I have a video source which is mpeg4 over rtsp
If I select "mov" or "mp4" via MPEG_LIVE_FORMAT, I get an error
?_write_header failed with error [whatever error EINVAL is on my OS] "invalid parameters"
and zms or nph-zms exits

Likewise, straight up running 
zmstreamer -o mp4
shows the same behavior [or -o mov]
gdb shows avformat_write_header() returning the badness

This is with version 1.28.1 on both Ubuntu and Solaris
[yes, Solaris - I've completed a port and would like to know where to submit the patches - just a pull request to here?]
Ubuntu 14 had .54 version of libavformat, I have .55 on OmniOS

Cheers

**Comment by knnniggett** [comment]
ZoneMinder currently transcodes all incoming video streams into jpeg's. So it really doesn't matter if the video source from the camera is mjpeg, mpeg4, h264, etc ....the result is the same.... jpeg's on the disk.

When it comes time to stream video from the zoneminder server to a client browser, ZoneMinder reassembles those jpegs back into a stream. By default, that stream is mpjeg, but you can change WEB_H_STREAM_METHOD under each Options -> B/W tab to stream MPEG, which finally brings us to MPEG_LIVE_FORMAT.  

As described in the help text, the only know working format is asf.  The invalid parameter message you are receiving when attempting mov & mp4 is due to the version of ffmpeg (or libav) on your system.  I don't get that error. The video makes it to my browser, but it still won't play. 

It is unlikely mov will ever work, and we don't currently have an answer as to why mp4 doesn't work.  
However, others have been successful streaming mpeg to their browsers, and I suggest you search this forum, our user forum, and the wiki for clues that others have left.

While I'm not denying this is an area that can be improved, we do not have the resources to put this on our priority list.  Instead, I encourage you to look forward to our upcoming video method, which records incoming video straight to an mp4 container.  I'd expect streaming from the zoneminder server to the client browser to work then, or at the very least be worth fixing at that point.
