### ISSUE TITLE
Web API for querying specific information

### ISSUE THREAD

**Issue by kylejohnson** [ZoneMinder/ZoneMinder#8]
I am tracking this work in my fork, in the 'api' branch.

**Comment by Yanson** [comment]
Is this in the latest release? I don't see it in the web root following these instructions: http://www.zoneminder.com/wiki/index.php/Ubuntu_Server_14.04_64-bit_with_Zoneminder_1.28.0_the_easy_way

**Comment by knnniggett** [comment]
@kylejohnson 
Do we just need to simply include everything under the web/api subfolder to the cmake & autotools scripts?  I can add that as an optional install item if that is all we need to do.  Let me know.

**Comment by kylejohnson** [comment]
The API gets installed corrected via cmake, but support isn't there yet for autotools.
@knnniggett In addition to installing web/api, the web/api/app/Config/ directory has a file or two that needs to be configured.  Check the cmakelists.txt file for more info as I can't recall it off the top of my head.

**Comment by devinellis** [comment]
Sorry to barge in on an old thread. I've been using Zoneminder at home for a couple months now and really like the "bones" of the project (event system, modect, zones, etc) and would really like to see a solid web API around it. 

I think a strong API could attract people (like me) looking to hack Zoneminder for their needs, would be great for mobile development, and the current front-end could be completely replaced with a simple UI around the API.

I took a look at the CakePHP API and there's not a lot there. I also noticed that it uses some Cake-specific data formatting that I find a bit uninviting (Model names included as response objects, non-JSON POST/PUT payloads). I guess I'm just wondering, why take the approach of side-stepping the rest of the PHP code to build a separate app that just interacts with MySQL? It seems like the smarter choice would be to migrate the current PHP codebase to become the API.

I know I'm probably just scratching the surface of the project but I would like to know what the long-term goals are with the PHP code.

**Comment by kylejohnson** [comment]
Hi @devinellis 

I too think that ZM's 'bones' are strong, and you're absolutely right, a good API would help significantly with (mobile) development.

The API work is now in the [angular-ui](https://github.com/ZoneMinder/ZoneMinder/tree/angular-ui) branch, where I have been developing an AngularJS-based frontend which does REST calls to the API.  I've been updating the API as needed, as the new UI does not use any server-side code.  That branch is ready for testing, but is not complete (would love assistance from someone that has built APIs before - I'm learning as I go).

You're right, I hate how Cake adds to model name to response object.  The newer API code in the angular-ui branch is using a 'Crud' plugin, which makes json responses much more sane, like what you'd expect in a modern API.  I'm slowly implementing Crud in the various models and controllers, and I wish I knew of this plugin on day 1.

My goal is to move ALL of the needed PHP code to the API, while re-factoring it to make sense within CakePHP's framework.  CakePHP does /a lot/ of the heavy lifting for us, so I definitely want to use it, especially for things like database interaction.  Cake also support authentication, so that code will be removed from the current PHP.  The rest of the code (e.g. generating videos) will be Cake-i-tized so that it can run within Cake's system and be called and used where needed.

Feel free to keep asking question and offering advice - I love to hear it.

Kyle

**Comment by devinellis** [comment]
@kylejohnson: Cool, glad you're already headed in the direction I was thinking. Is there any way we can move the Angular/API rewrite to a feature branch, and start making smaller PRs to it? Your angular-ui branch is huge, and I'd like to start leaving some feedback. I opened #744 to help clean things up.

**Comment by kylejohnson** [comment]
@devinellis Sounds good, but what are some of your specific recommendations?  The angular-ui is already in a feature branch, and it makes sense (from my perspective anyway) to be able to develop the API along with the client.

**Comment by devinellis** [comment]
Since there isn't a PR for it yet there is no good place for me to leave feedback. Since we know all the UI and API changes to get this to work will be a massive diff, merging in smaller bits at a time into the feature branch would be better IMO. When it's complete the feature branch can be merged in to master. I understand needing to do API and UI work simultaneously, so maybe break it up by feature, or view?

**Comment by kylejohnson** [comment]
I think that is a good idea (split it up by feature or view).  What do you propose we do with the current changes?

Kyle

**Comment by devinellis** [comment]
I guess you could start by creating a PR for what you have now, and we can move the discussion there.

**Comment by kylejohnson** [comment]
@devinellis I don't want to merge any of this code into master until we have something that is ready to be used - whatever that might mean.

**Comment by devinellis** [comment]
Exactly. So I'd suggest we create a PR of this branch into a "feature" branch (I know this is the feature branch). That way we can review what you have, and future work can be made into smaller PRs into that feature branch. When ready, we merge that feature branch into master, having reviewed it as separate PRs already.

**Comment by arjunroychowdhury** [comment]
Hi, I am already in the process of building a mobile app - basic screens are working. More details here http://www.zoneminder.com/forums/viewtopic.php?f=32&t=23073  --> I will soon be open sourcing it (in a month or so - as soon as I get all screens done and the data models abstracted out) in the hope that others can fork and innovate. Given that you are using AngularJS, I decided to learn AngularJS and implement it in the client too.

Are there any plans of making this mainstream - aka:
1) It gets installed as part of a package install (I suspect most people are using repos/ppa and not compiling source. And those few who compile source use the dpkg route and not cmake)

2) Is it possible that as part of your automated install, you also put in instructions or a script to automatically add a CORS heads to Apache? Otherwise browsers on desktops will reject request responses to the ZM server (not a mobile problem, but a cross platform app that works on desktops will have this problem). One can use JSONP but a better approach is CORS compliance (I think)

3) Right now I am forced to use skin=xml for most views and basically trace API requests the web interface is using via httpry to see how to emulate them in the app - not an ideal approach

4) When you do install the APIs, can you also make sure it works with authentication and does not return information without auth?

**Comment by knnniggett** [comment]
The web API is currently in the master branch and is in testing.  I'm going to close this issue out since it regards the former API feature branch and has become out of date.
