### ISSUE TITLE
Exportable Camera Configs

### ISSUE THREAD

**Issue by knight-of-ni** [ZoneMinder/zoneminder#86]
Here is a feature suggestion for a future release.
It would be helpful if we could easily export camera configurations, including the ptz control file, and be able to exchange them with others, who could then import those configs as presets into their own zoneminder systems.

**Comment by jpmorris** [comment]
+1  Is zoneminder doing something different -- namely, storing configs in the database as opposed to a flatfile -- that other database-dependent projects dont do?  I am running pihole, homeassistant, plex, crashplan, and many others make a flatfile config work somehow.  Zabbix integrates config in the database but at leas thas the ability to export configs. 

I'm in need of this function because I try and backup my config (don't care so much about the data) to a synology box via samba.  BUT I also run all the services above and zoneminder in docker containers.  So now I have to mess with a docker/samba permission barrier to try and get samba to backup mysql instead of a flatfile.  I haven't found how how yet, and I've had to reconfigure twice becuase I've borked something (most recentiliy by trying to change some permissions or something and couldn't get it back together again.)
