### ISSUE TITLE
incorrect encoding of Russian language

### ISSUE THREAD

**Issue by edgiru** [ZoneMinder/ZoneMinder#907]
when opening a file transfer ru_RU on github
not read words and letters.

![default](https://cloud.githubusercontent.com/assets/4624056/8364024/b70996fc-1b8b-11e5-8fa6-d073ec60e67a.JPG)

when opening a file transfer ru_RU on github
not read words and letters. I tried different encoding utf-8, windows-1251, KOI8-R, KOI8-U google chrome browser is not which character did not help make the text readable.

**Comment by seeebek** [comment]
Download the file to your PC and open with a proper editor capable of handling different encodings (e.g. notepad++ on Windows). It should recognize the encoding directly. If not,  you can select KOI8-R from the menu.

You cannot do it in webbrowser on github because github is utf-8 encoded, you have to download it first.

**Comment by edgiru** [comment]
thanks
