### ISSUE TITLE
virtualbox - zoneminder shows only six cams

### ISSUE THREAD

**Issue by z-impi** [ZoneMinder/ZoneMinder#927]
Hello,

zoneminder let me only view six of the 12 cams in a virtualbox. 
The same configuration is working fine on a hardware machine and qemu.
I thought it is an virtualbox bridging error but could determine that it isn't. 
But I cant rule out the possibility of an virtualbox error. 
I checked with wireshark if and how the packages are sent and received.

![shot01](https://cloud.githubusercontent.com/assets/13234767/8567643/5d39a212-2567-11e5-905a-67c7d1c83fd3.png)

Theese cams are of the exact same model. And are working fine on an hardware machine.
Has anyone else experienced this yet?

**Comment by knnniggett** [comment]
First guess is a lack of physical memory.  

However, this issue does not describe a bug or a feature request.
This is configuration issue that should be discussed in the zoneminder user forum.

When posting in the user forum, you need to:
a) post your logs. 
b) post your entire camera config

Otherwise, we are just guessing.
